config/routes.rb
Rails.application.routes.draw do
  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'boards#index'

  get '/boards/:trello', to: 'boards#show'
  resources :users, :roles, :boards
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/met.rb
module Met
  extend ActiveSupport::Concern

  def get_boards
  	@accessTrello ||= Trello::Member.find(idTrello)
  	boards = @accessTrello.boards
  	boards
  end

  def get_cards(idboard)
  	connect = @accessTrello
    @accessBoard ||= Trello::Board.find(idboard)
  	@cards = @accessBoard.cards
  end

  def get_list(idboard)
    connect = @accessTrello
    @accessBoard ||= Trello::Board.find(idboard)
    @list = @accessBoard.lists
  end

end

app/models/permission.rb
class Permission < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	include Met
	validates :username, :password, :role, :first_name, :last_name, presence: true
	def self.permitted_params
  	[:username, :first_name, :last_name, :idTrello, :role_id, :password,  :password_confirmation]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  layout 'admin'
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

	def index
		@boards = User.find(4).get_boards
	end

	def show
		@boardslists = User.find(4).get_list(params[:trello])
		@boardscards = User.find(4).get_cards(params[:trello])
	end
end

app/controllers/role_controller.rb
class RoleController < Inheritance::RoleController
	layout 'admin'
end

app/controllers/sessions_controller.rb
class SessionsController < Inheritance::SessionsController
	private
	  def session_paths(role_name)
	  	{'Admin' => users_path}[role_name] || root_path
	  end
end

app/controllers/users_controller.rb
class UsersController < Inheritance::ControllerAccess
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/role_helper.rb
module RoleHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/index.html.erb
<p id="notice"><%= notice %></p>

<center><h1>Boards</h1>
</center>

<div class="row">
<% @boards.each do |board| %>
  <div class="col-sm-4 col-lg-4 col-md-4">
   <div class="thumbnail">
    <div class="caption">
    <center>

      <h4><%= link_to board.name, :controller => "boards", :action => "show", :trello => board.id %></h4>
      <br>

    </center>
    </div>
    </div>
  </div>


<% end %>
</div>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<center><h1>Cards</h1></center>
<div class="row">
<% @boardslists.each do |list| %>



   <div class="thumbnail">
  <%= list.name%>
<% listid = list.id %>

<div class="row">
<% @boardscards.each do |cards| %>
<% if listid == cards.list_id %>
  <div class="col-sm-4 col-lg-4 col-md-4">
   <div class="thumbnail">
    <div class="caption">
    <center>

     <%= cards.name %>

    </center>
    </div>
    </div>
  </div>
<% end %>

<% end %>
</div>

</div>
<% end %>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-shadow bg-dark">
  <div class="navbar-branding">
    <a class="navbar-brand pt10" href="/">
      <!-- <%# load_svg 'logo/logo', :png, 'img-responsive' %> -->
      <b>Bitlab</b>Admin
    </a>
    <span id="toggle_sidemenu_l" class="ad ad-lines"></span>
  </div>
  <ul class="nav navbar-nav navbar-right">
    <li>
      <div class="navbar-btn btn-group">
        <%= topbar_menu_toggle 'fa fa-plus' %>
      </div>
    </li>
    <%= navbar_divider %>
    <%= navbar_dropdown current_user.full_name do %>
      <%= navbar_dropdown_footer ' Cerrar sesión', 'users_logout_path', 'fa fa-power-off' %>
    <% end %>
  </ul>
</header>

app/views/layouts/_sidebar.html.erb
<%= sidebar color: 'sidebar-light' do %>
  <%= render '/layouts/sidebar/menu' %>
<% end %>

app/views/layouts/_topbar.html.erb
<% @topbar ||= false %>
<% if @topbar || !content_for?(:topbar) %>
  <% if inherited_controller? %>
    <header id="topbar" class="alt">
      <div class="topbar-left">
        <ol class="breadcrumb">
          <li class="crumb-active">
            <a href="<%= polymorphic_path([namespace, object_class]) %>">
              <%= controller_name.classify.constantize.model_name.human count: 2 %>
            </a>
          </li>
          <li class="crumb-trail"><%= t "actions.#{params[:action]}" %></li>
        </ol>
      </div>
      <div class="topbar-right">
        <% (@links || []).each do |link| %>
          <%= link_to link[1][:title], link[1][:path], class: link[1][:class] || 'btn btn-primary', method: link[1][:method] || 'delete', style: "display: #{link[1].try(:[], :options).try(:[], :enabled)}" || '' %>
        <% end %>
        <div class="btn-group">
          <% if !content_for?(:tools) %>
            <button type="button" class="btn btn-dark" onclick="location.href='<%= new_polymorphic_path([namespace, object_class]) %>'">
              <i class="fa fa-plus"></i>
            </button>
          <% end %>
        </div>
      </div>
    </header>
  <% end %>
<% else %>
  <%= yield :topbar %>
<% end %>

app/views/layouts/_topbar_dropdown.html.erb
<%= topbar_dropmenu do %>
  <div class="col-xs-3 col-sm-3">
    <%= metro_link 'Button 1', 'path', 'bg-primary', 'fa fa-github-alt' %>
  </div>
  <div class="col-xs-3 col-sm-3">
    <%= metro_link 'Button 2', 'path', 'bg-warning', 'fa fa-github-square' %>
  </div>
  <div class="col-xs-3 col-sm-3">
    <%= metro_link 'Button 3', 'path', 'edicion', 'fa fa-html5' %>
  </div>
  <div class="col-xs-3 col-sm-3">
    <%= metro_link 'Button 4', 'path', 'bg-system', 'fa fa-gamepad' %>
  </div>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>App</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= favicon_link_tag 'favicon.ico', rel: 'shortcut icon' %>
  <%= javascript_include_tag 'application' %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
  <![endif]-->
</head>

<%= body 'charts-highcharts-page sb-l-o sb-r-c onload-check' do %>

  <div id="main">

    <%= render '/layouts/header' %>
    <%= render '/layouts/sidebar' %>

    <section id="content_wrapper">

      <%= render '/layouts/topbar_dropdown' %>
      <%= render '/layouts/topbar' %>

      <section id="content" class="animated fadeIn">
        <%= yield %>
      </section>

    </section>

    <%= render '/layouts/sidebar/right' %>

  </div>

<% end %>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BitlabAdmin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/sidebar/_menu.html.erb
<ul class="nav sidebar-menu">
  <li class="sidebar-label pt20">Menu</li>
  <%= sidebar_icon_accordion 'Home', 'fa fa-home' do  %>
    <%= accordion_icon_link 'Users', users_path, nil, nil %>
    <%= accordion_icon_link 'Boards', boards_path, nil, nil %>
    <%= accordion_icon_link 'Home', root_path, nil, nil %>
  <% end %>
</ul>

app/views/layouts/sidebar/_right.html.erb
<aside id="sidebar_right" class="nano affix">

  <!-- Start: Sidebar Right Content -->
  <div class="sidebar-right-content nano-content p15">
      <h5 class="title-divider text-muted mb20"> Server Statistics
        <span class="pull-right"> 2013
          <i class="fa fa-caret-down ml5"></i>
        </span>
      </h5>
      <div class="progress mh5">
        <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 44%">
          <span class="fs11">DB Request</span>
        </div>
      </div>
      <div class="progress mh5">
        <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 84%">
          <span class="fs11 text-left">Server Load</span>
        </div>
      </div>
      <div class="progress mh5">
        <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 61%">
          <span class="fs11 text-left">Server Connections</span>
        </div>
      </div>
      <h5 class="title-divider text-muted mt30 mb10">Traffic Margins</h5>
      <div class="row">
        <div class="col-xs-5">
          <h3 class="text-primary mn pl5">132</h3>
        </div>
        <div class="col-xs-7 text-right">
          <h3 class="text-success-dark mn">
            <i class="fa fa-caret-up"></i> 13.2% </h3>
        </div>
      </div>
      <h5 class="title-divider text-muted mt25 mb10">Database Request</h5>
      <div class="row">
        <div class="col-xs-5">
          <h3 class="text-primary mn pl5">212</h3>
        </div>
        <div class="col-xs-7 text-right">
          <h3 class="text-success-dark mn">
            <i class="fa fa-caret-up"></i> 25.6% </h3>
        </div>
      </div>
      <h5 class="title-divider text-muted mt25 mb10">Server Response</h5>
      <div class="row">
        <div class="col-xs-5">
          <h3 class="text-primary mn pl5">82.5</h3>
        </div>
        <div class="col-xs-7 text-right">
          <h3 class="text-danger mn">
            <i class="fa fa-caret-down"></i> 17.9% </h3>
        </div>
      </div>
      <h5 class="title-divider text-muted mt40 mb20"> Server Statistics
        <span class="pull-right text-primary fw600">USA</span>
      </h5>
    </div>

</aside>